#!/usr/bin/bash

# Placer le script dans ~/.local/share/nautilus/scripts/ (pour GNOME) ou ~/.local/share/nemo/scripts/ (pour Cinnamon)
# Ne pas oublier de le rendre exécutable !

if [[ ! $(which gs) ]] ; then
  notify-send 'Compresser et aplatir les PDFs' 'Erreur : la commande "ghostscript" n’est pas installée.'
  exit 1
fi

case $(printf "${XDG_SESSION_DESKTOP}") in
  gnome|ubuntu) readarray -t selection <<< $(echo "${NAUTILUS_SCRIPT_SELECTED_FILE_PATHS}" | sed 's/^$//g') ;;
  cinnamon) readarray -t selection <<< $(echo "${NEMO_SCRIPT_SELECTED_FILE_PATHS}" | sed 's/^$//g') ;;
esac

for fichier in "${selection[@]}" ; do
    nom=$(basename -a -s .pdf "${fichier}")
    ps2pdf -dNumRenderingThreads=4 "${fichier}" - | \
    gs -dSAFER -dBATCH -dNOPAUSE -sDEVICE=pdfwrite -dPreserveAnnots=false -sOutputFile="${nom}_compressé_aplati.pdf" -
done

notify-send --hint=int:transient:1 'Compresser et aplatir les PDFs' 'Terminé.'
