#!/usr/bin/bash

# Placer le script dans ~/.local/share/nautilus/scripts/ (pour GNOME) ou ~/.local/share/nemo/scripts/ (pour Cinnamon)
# Ne pas oublier de le rendre exécutable !

if [[ ! $(which jpegoptim) ]] ; then
  notify-send 'Compression sans perte des images' 'Erreur : la commande "jpegoptim" n’est pas installée.'
  exit 1
fi
if [[ ! $(which optipng) ]] ; then
  notify-send 'Compression sans perte des images' 'Erreur : la commande "optipng" n’est pas installée.'
  exit 1
fi

case $(printf "${XDG_SESSION_DESKTOP}") in
  gnome|ubuntu) readarray -t selection <<< $(echo "${NAUTILUS_SCRIPT_SELECTED_FILE_PATHS}" | sed 's/^$//g') ;;
  cinnamon) readarray -t selection <<< $(echo "${NEMO_SCRIPT_SELECTED_FILE_PATHS}" | sed 's/^$//g') ;;
esac

for fichier in "${selection[@]}" ; do
    jpegoptim --preserve "${fichier}" || \
    optipng "${fichier}"   
done

notify-send --hint=int:transient:1 'Compression sans perte des images' 'Terminé.'
