#!/usr/bin/bash

# Placer le script dans ~/.local/share/nautilus/scripts/ (pour GNOME) ou ~/.local/share/nemo/scripts/ (pour Cinnamon)
# Ne pas oublier de le rendre exécutable !

if [[ ! $(which convert) ]] ; then
  cat > "Installer convert.txt" << EOF
convert se trouve la plupart du temps dans le paquet "imagemagick" ou "ImageMagick".
L’installer pour Ubuntu, Linux Mint, Debian et derivés :
sudo apt install imagemagick
L’installer pour Fedora, CentOS, RHEL et dérivés :
sudo dnf install ImageMagick

Si après l’installation vous obtenez l’erreur suivante :
convert-im6.q16: attempt to perform an operation not allowed by the security policy \`PDF' @ error/constitute.c/IsCoderAuthorized/408.
Lancez cette commande :
sudo sed -i_bak 's/rights="none" pattern="PDF"/rights="read | write" pattern="PDF"/' /etc/ImageMagick-6/policy.xml
EOF
  notify-send 'Rassembler les images dans un PDF' 'Erreur : la commande "convert" n’est pas installée. Les instructions d’installation sont consultables dans le fichier "Installer convert".'
  exit 1
fi

case $(printf "${XDG_SESSION_DESKTOP}") in
  gnome|ubuntu) readarray -t selection <<< $(echo "${NAUTILUS_SCRIPT_SELECTED_FILE_PATHS}" | sed 's/^$//g') ;;
  cinnamon) readarray -t selection <<< $(echo "${NEMO_SCRIPT_SELECTED_FILE_PATHS}" | sed 's/^$//g') ;;
esac

convert "${selection[@]}" compilation_images.pdf 2>> compilation_images.log

if [[ "${?}" -ne 0 ]] ; then
  echo "$(date '+%FT%T')" >> compilation_images.log
  echo >> compilation_images.log
  notify-send 'Rassembler les images dans un PDF' 'Une ou plusieurs erreurs ont été rencontrées. Voir le fichier compilation_images.log pour les détails.'
else
  if [[ -z $(cat compilation_images.log) ]] ; then rm compilation_images.log ; fi
  notify-send --hint=int:transient:1 'Rassembler les images dans un PDF' 'Terminé avec succès.'
fi
