#!/usr/bin/bash

case $(printf "${XDG_SESSION_DESKTOP}") in
  gnome|ubuntu) readarray -t selection <<< $(echo "${NAUTILUS_SCRIPT_SELECTED_FILE_PATHS}" | sed 's/^$//g') ;;
  cinnamon) readarray -t selection <<< $(echo "${NEMO_SCRIPT_SELECTED_FILE_PATHS}" | sed 's/^$//g') ;;
esac

feh \
  --fullscreen \
  --zoom max \
  --hide-pointer \
  --draw-filename \
  --randomize \
  --recursive \
  --slideshow-delay 4 \
  --fontpath ${HOME}/.config/feh \
  --font NanumBarunGothic/12 \
  "${selection[@]}"
